export interface BussinessComponent {
  bannerImage:string,
  description:string,
  email:string,
  firstName:string,
  id:number,
  image:string,
  lastName:string,
  password:string,
  phone:string,
  role : string,
  name: string,
  ruc: string,
  owner: string,
  address: string,
  locality: string,
  city: string,
}
